// This is a test.ts file generated by GitHub Actions using TypeScript.
// It contains dummy comments and should not be modified directly.

interface MyInterface {
  myFunction: () => void;
}

let myObject: MyInterface = { myFunction: () => {} };

myObject.myFunction();
